### ISSUE TITLE
Regarding the Code Organization

### ISSUE THREAD

**Issue by gchhablani** [anton-l/wav2vec-toolkit#4]
Recently, I came across Facebook AI's MMF repository which had this registry feature which I find really cool. Since then, I have followed the same code organization for my projects. One of them you can find at https://github.com/gchhablani/toxic-spans-detection

 Basically, there is one registry (or what I call it - `configmapper`). Every run has a YAML config, and using the registry and YAML config, we load objects/classes in the script.

I'm not sure if we can do the same here, but some basic organization for experiments could follow similar structure. Let me know your thoughts on this.

**Comment by anton-l** [comment]
If we add W&B experiment tracking and hyperparam sweeps, like @borisdayma suggested, then we can just expose all params via cmd args, without explicit configs. Wouldn't that be easier/faster to implement?

**Comment by gchhablani** [comment]
@anton-l That's actually much better. The only reason to have configs is to save the params in one place, and I guess W&B is much better for that.

Closing.

**Comment by borisdayma** [comment]
There's a lot of ways to use wandb. I understand from it that we're gonna do a combination wandb + argparse (I guess the huggingface parser kind). It's actually pretty straightforward.
I should be able to set up something this week for it.
